import { b as bootstrapLazy } from './index-DqB_q70x.js';
export { s as setNonce } from './index-DqB_q70x.js';
import { g as globalScripts } from './app-globals-DQuL1Twl.js';

const defineCustomElements = async (win, options) => {
  if (typeof window === 'undefined') return undefined;
  await globalScripts();
  return bootstrapLazy([["checkbox-field",[[774,"checkbox-field",{"field":[16],"isChecked":[4,"is-checked"],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"isTouched":[32]}]]],["date-field",[[772,"date-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"isTouched":[32]}]]],["file-field",[[772,"file-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"isTouched":[32]}]]],["form-legend",[[768,"form-legend",{"field":[16]}]]],["input-field",[[772,"input-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"isTouched":[32]}]]],["multifile-field",[[772,"multifile-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"]}]]],["number-field",[[772,"number-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"value":[32],"isTouched":[32]}]]],["phone-number-field",[[772,"phone-number-field",{"field":[16],"language":[1],"isInvalid":[4,"is-invalid"],"isHidden":[4,"is-hidden"],"isDisabled":[4,"is-disabled"],"values":[32],"isTouched":[32]}]]],["radio-field",[[774,"radio-field",{"field":[16],"value":[8],"isInvalid":[4,"is-invalid"],"isDisabled":[4,"is-disabled"],"isHidden":[4,"is-hidden"],"isTouched":[32]}]]],["select-field",[[772,"select-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isHidden":[4,"is-hidden"],"isDisabled":[4,"is-disabled"],"isTouched":[32]}]]],["textarea-field",[[772,"textarea-field",{"field":[16],"isHidden":[4,"is-hidden"],"isDisabled":[4,"is-disabled"],"isInvalid":[4,"is-invalid"],"isTouched":[32]}]]],["toggle-field",[[772,"toggle-field",{"field":[16],"isChecked":[4,"is-checked"],"isInvalid":[4,"is-invalid"],"isHidden":[4,"is-hidden"],"isDisabled":[4,"is-disabled"],"isTouched":[32]}]]],["typeahead-field",[[772,"typeahead-field",{"field":[16],"isInvalid":[4,"is-invalid"],"isHidden":[4,"is-hidden"],"isDisabled":[4,"is-disabled"],"isTouched":[32],"isOpen":[32],"filtered":[32],"highlightedIndex":[32]}]]],["yaseer-watermark",[[258,"yaseer-watermark"]]],["form-builder_2",[[769,"yaseer-form",{"componentSettings":[1,"component-settings"],"formFields":[32],"settings":[32],"isSubmitting":[32],"getFormValues":[64],"toggleSpinner":[64],"submitForm":[64]}],[772,"form-builder",{"formId":[1,"form-id"],"formFields":[16],"language":[1],"actionUrl":[1,"action-url"],"sortedFields":[32],"getFormValues":[64],"handleSubmit":[64]},[[0,"fieldBlurred","handleFieldBlurred"],[0,"valueChanged","handleValueChange"]]]]]], options);
};

export { defineCustomElements };
//# sourceMappingURL=loader.js.map
